name: iOS Starter Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and Test default scheme using any available iPhone simulator
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.1"

      - name: List Available Devices and Runtimes
        run: |
          echo "Available devices and simulators:"
          xcrun xctrace list devices
          echo "Available simulator runtimes:"
          xcrun simctl list runtimes

      - name: Set Default Scheme
        run: |
          scheme_list=$(xcodebuild -list -json | tr -d "\n")
          if [ -z "$scheme_list" ]; then
            echo "Error: xcodebuild did not return valid JSON."
            exit 1
          fi
          default=$(echo $scheme_list | ruby -e "require 'json'; puts JSON.parse(STDIN.gets)['project']['targets'][0]")
          echo $default | cat >default
          echo Using default scheme: $default

      - name: Build
        env:
          scheme: ${{ 'default' }}
          platform: ${{ 'iOS Simulator' }}
        run: |
          # Select an iPhone simulator with iOS 18.2
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone[^)]*\(18\.2[^)]*\)' | head -1 | awk -F'(' '{print $1}' | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          if [ -z "$device" ]; then
            echo "Error: No iPhone simulator with iOS 18.2 found."
            xcrun xctrace list devices
            exit 1
          fi
          echo "Selected device: $device"
          if [ "$scheme" = "default" ]; then scheme=$(cat default); fi
          if [ "$(ls -A | grep -i \\.xcworkspace$)" ]; then filetype_parameter="workspace" && file_to_build="$(ls -A | grep -i \\.xcworkspace$)"; else filetype_parameter="project" && file_to_build="$(ls -A | grep -i \\.xcodeproj$)"; fi
          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
          xcodebuild build-for-testing -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device,OS=18.2"

      - name: Test
        env:
          scheme: ${{ 'default' }}
          platform: 'iOS Simulator'
        run: |
          # Select the same iPhone simulator as in the Build step
          device=$(xcrun xctrace list devices 2>&1 | grep -oE 'iPhone[^)]*\(18\.2[^)]*\)' | head -1 | awk -F'(' '{print $1}' | awk '{$1=$1;print}' | sed -e "s/ Simulator$//")
          if [ -z "$device" ]; then
            echo "Error: No iPhone simulator with iOS 18.2 found."
            xcrun xctrace list devices
            exit 1
          fi
          echo "Selected device: $device"
          if [ "$scheme" = "default" ]; then scheme=$(cat default); fi
          if [ "$(ls -A | grep -i \\.xcworkspace$)" ]; then filetype_parameter="workspace" && file_to_build="$(ls -A | grep -i \\.xcworkspace$)"; else filetype_parameter="project" && file_to_build="$(ls -A | grep -i \\.xcodeproj$)"; fi
          file_to_build=$(echo $file_to_build | awk '{$1=$1;print}')
          xcodebuild test-without-building -scheme "$scheme" -"$filetype_parameter" "$file_to_build" -destination "platform=$platform,name=$device,OS=18.2"